# Generated by Django 5.0.3 on 2024-03-23 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('anime_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimeTitles.animetitle')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnimeTitles.genre')),
            ],
        ),
        migrations.AddField(
            model_name='animetitle',
            name='genres',
            field=models.ManyToManyField(through='AnimeTitles.AnimeGenre', to='AnimeTitles.genre'),
        ),
    ]
