# Generated by Django 5.0.3 on 2024-03-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeTitles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetitle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anime_images/'),
        ),
    ]
