# Generated by Django 5.0.3 on 2024-03-26 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeTitles', '0002_animetitle_image'),
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anime_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AnimeTitles.animetitle'),
        ),
    ]
