# Generated by Django 5.0.3 on 2024-04-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_review_anime_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='value',
            new_name='rating',
        ),
    ]
