# Generated by Django 5.0.3 on 2024-04-02 21:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeTitles', '0002_animetitle_image'),
        ('Reviews', '0003_rename_value_rating_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'anime_title')},
        ),
    ]
