# Generated by Django 5.0.3 on 2024-04-03 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAnimeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Source',
            new_name='ExternalSource',
        ),
        migrations.RemoveField(
            model_name='externalreview',
            name='anime_title',
        ),
        migrations.RemoveField(
            model_name='externalreview',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='externalreview',
            name='rating',
        ),
        migrations.AddField(
            model_name='externalreview',
            name='external_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sources.externalanimetitle'),
        ),
        migrations.AddField(
            model_name='externalreview',
            name='external_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sources.externaluser'),
        ),
    ]
