# Generated by Django 5.0.3 on 2024-04-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sources', '0002_externalanimetitle_externaluser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalreview',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
